name: "LintPRTitle"
on:
    pull_request_target:
        types:
            - opened
            - edited
            - synchronize
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            # Please look up the latest version from here
            # https://github.com/amannn/action-semantic-pull-request/releases
            - uses: amannn/action-semantic-pull-request@7bfb19c48fc334d3dacb072cf982e81535041209 # v3.4.6
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
