name: "LintPRTitle"
on:
    pull_request_target:
        types:
            - opened
            - edited
            - synchronize
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            # Please look up the latest version from here
            # https://github.com/amannn/action-semantic-pull-request/releases
            - uses: amannn/action-semantic-pull-request@536f681e2c60d973396eb60457d42ced8cd3f61a # v3.7.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
