name: "LintPRTitle"
on:
    pull_request_target:
        types:
            - opened
            - edited
            - synchronize
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            # Please look up the latest version from here
            # https://github.com/amannn/action-semantic-pull-request/releases
            - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
